// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqNUtkumXQjox1e2OIiT_zujM9N9FpCNA',
    appId: '1:359129399832:android:d44f779887480ac872796d',
    messagingSenderId: '359129399832',
    projectId: 'wallpaper-5ea38',
    storageBucket: 'wallpaper-5ea38.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrnTANKgrQJ5RXCuJ9C62UNDwlnDmEoH4',
    appId: '1:359129399832:web:fb383d1e1e6e0a5872796d',
    messagingSenderId: '359129399832',
    projectId: 'wallpaper-5ea38',
    authDomain: 'wallpaper-5ea38.firebaseapp.com',
    storageBucket: 'wallpaper-5ea38.firebasestorage.app',
    measurementId: 'G-4JXC95DL7R',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrnTANKgrQJ5RXCuJ9C62UNDwlnDmEoH4',
    appId: '1:359129399832:web:07b37b1f649664b272796d',
    messagingSenderId: '359129399832',
    projectId: 'wallpaper-5ea38',
    authDomain: 'wallpaper-5ea38.firebaseapp.com',
    storageBucket: 'wallpaper-5ea38.firebasestorage.app',
    measurementId: 'G-6B7HCZZ2B9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAILIcVlIehDc2OI7SG8CsiL7Ua_lNPWuU',
    appId: '1:359129399832:ios:144772a0b7deddd672796d',
    messagingSenderId: '359129399832',
    projectId: 'wallpaper-5ea38',
    storageBucket: 'wallpaper-5ea38.firebasestorage.app',
    iosBundleId: 'com.example.wallpaper',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAILIcVlIehDc2OI7SG8CsiL7Ua_lNPWuU',
    appId: '1:359129399832:ios:144772a0b7deddd672796d',
    messagingSenderId: '359129399832',
    projectId: 'wallpaper-5ea38',
    storageBucket: 'wallpaper-5ea38.firebasestorage.app',
    iosBundleId: 'com.example.wallpaper',
  );

}