// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi-F5roX5PJ0_Mp9aQef5rLrxpugUU160',
    appId: '1:606723884671:android:54cdb1e052767e746e214a',
    messagingSenderId: '606723884671',
    projectId: 'wall-pix-535f4',
    storageBucket: 'wall-pix-535f4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG_u30N1yoBzR8-pwT7fUuJcSKICB21mg',
    appId: '1:606723884671:web:2b387772ede6f5866e214a',
    messagingSenderId: '606723884671',
    projectId: 'wall-pix-535f4',
    authDomain: 'wall-pix-535f4.firebaseapp.com',
    storageBucket: 'wall-pix-535f4.firebasestorage.app',
    measurementId: 'G-1WJY2NT3PJ',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG_u30N1yoBzR8-pwT7fUuJcSKICB21mg',
    appId: '1:606723884671:web:6e0701d024310c126e214a',
    messagingSenderId: '606723884671',
    projectId: 'wall-pix-535f4',
    authDomain: 'wall-pix-535f4.firebaseapp.com',
    storageBucket: 'wall-pix-535f4.firebasestorage.app',
    measurementId: 'G-F1J6X72WWG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPH63lLRQDhYGAJuiRNQmBLeK0-23ngvM',
    appId: '1:606723884671:ios:13a2a2bc36764ded6e214a',
    messagingSenderId: '606723884671',
    projectId: 'wall-pix-535f4',
    storageBucket: 'wall-pix-535f4.firebasestorage.app',
    iosBundleId: 'com.example.wallpaper',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPH63lLRQDhYGAJuiRNQmBLeK0-23ngvM',
    appId: '1:606723884671:ios:13a2a2bc36764ded6e214a',
    messagingSenderId: '606723884671',
    projectId: 'wall-pix-535f4',
    storageBucket: 'wall-pix-535f4.firebasestorage.app',
    iosBundleId: 'com.example.wallpaper',
  );

}